---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hermkdmx/public_html/language-journal
    - /bin/cp -R build/* $DEPLOYPATH
    - /bin/cp -R server $DEPLOYPATH/server
    - /bin/chmod 755 $DEPLOYPATH/server/*.js