---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hermkdmx/public_html
    - /bin/cp -R language-journal/build/* $DEPLOYPATH
    - /bin/cp -R server $DEPLOYPATH/server
    - /bin/cp -R python_api $DEPLOYPATH/python_api
    - /bin/chmod 755 $DEPLOYPATH/python_api/*.py
    - /bin/chmod 755 $DEPLOYPATH/server/*.js